name: Deploy Hugo

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Download hugo_math
        run: |
          wget https://github.com/rzy0901/hugo/releases/download/v1.0.0/hugo_math
          chmod +x hugo_math
      - name: Build
        run: ./hugo_math --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          publish_dir: ./public
